_target_: watchmal.model.swintSI.SwinRegressor

img_size: [192, 192]
in_chans: 2
num_output_channels: 3
use_conv_stem: false
pre_stage_patch_size: 2
pre_stage_embed_dim: 48
pre_stage_depth: 8
pre_stage_num_heads: 6
pre_stage_window_size: 4
embed_dim: 96
depths: [4, 4, 10, 2]
num_heads: [3, 6, 12, 24]
window_size: 6
ape: true
drop_path_rate: 0
