_target_: watchmal.engine.regression.MultiTaskRegressionEngine
target_key: [directions, positions, energies]
target_scale_factor:
  directions: 1
  positions: 4000
  energies: 2000
target_scale_offset:
  directions: 0
  positions: 0
  energies: 0
