defaults:
    - data: iwcd_postveto_nomichel
    - data/dataset: iwcd_cnn
    - model: classifier
    - model/feature_extractor: pointnet
    - model/classification_network: pointnet_fc
    - engine: classifier
    - tasks/train: train_pointnet
    - optimizer@tasks.train.optimizer: adam
    - sampler@tasks.train.train_data.sampler: subset_random
    - sampler@tasks.train.validation_data.sampler: subset_sequential
    - tasks/evaluate: test
    - sampler@tasks.evaluate.data.sampler: subset_sequential
