defaults:
    - data: iwcd_postveto_nomichel
    - data/dataset: iwcd_cnn
    - model: classifier
    - model/feature_extractor: resnet18
    - model/classification_network: resnet_fc
    - optimizer: adam
    - engine: classifier
    - load_model: '/home/jtindall/new_framework_replication_run/run_4_1_gpu/ClassifierBEST.pth'
    - train: train_resnet
    - test: test_resnet