gpu_list:
    - 0
seed: null
dump_path: './outputs/'
defaults:
    - data: 4_class_test_run1
    - data/dataset: iwcd_cnn_short
    - model: classifier
    - model/feature_extractor: resnet18
    - model/classification_network: resnet_fc
    - engine: classifier
    - tasks/restore_state: restore_state
    - tasks/evaluate: test
    - sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential