gpu_list:
  - 0
seed: 42
dump_path: './outputs/'
defaults:
  - data: vitdi_data
  - model: swinDI
  - engine: regression_DI
  - tasks/train: train_transformer
  - tasks/restore_best_state: restore_best_state
  - tasks/evaluate: test
  - override optimizers@tasks.train.optimizers: muon
  - override scheduler@tasks.train.scheduler: cosinelr
  - override loss@tasks.train.loss: huber_costum
  - override loss@tasks.evaluate.loss: huber_costum
  - _self_
