data:
  split_path: '/fast_scratch_2/aferreira/t2k/ml/data/oct20_combine_flatE/train_val_test_nFolds3_fold0.npz' 
  dataset:
    h5file: '/fast_scratch_2/aferreira/t2k/ml/data/oct20_combine_flatE/combine_combine.hy'
    _target_: watchmal.dataset.cnn.cnn_dataset.CNNDataset
    pmt_positions_file: /fast_scratch/WatChMaL/data/T2K/image_files/skdetsim_imagefile.npy
    channel_scaling:
      time: [950, 10]
model:
  _target_: watchmal.model.resnet.resnet18
  num_input_channels: 2
  num_output_channels: 3
  stride: 1
  kernelSize: 1
  dropout_p: 0.3
engine:
  _target_: watchmal.engine.regression.RegressionEngine
  truth_key: 'positions'
tasks:
  restore_best_state:
    name: RegressionEngine_ResNet
  evaluate:
    loss:
      _target_: torch.nn.HuberLoss
      delta: 0.1
    optimizers:
      _target_: torch.optim.Adam
      lr: 0.001
      weight_decay: 0
    data_loaders:
      test:
        split_key: test_idxs
        batch_size: 512
        num_workers: 2
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
gpu_list: 
- 6
- 7
seed: null
dump_path: ./outputs/
