data:
  split_path: '/fast_scratch_2/fcormier/t2k/jan24_electronsOnly_5M//train_val_test_nFolds10_fold7.np' 
  dataset:
    h5file: '/fast_scratch_2/fcormier/t2k/jan24_electronsOnly_5M/digi_combine.hy'
    _target_: watchmal.dataset.cnn.cnn_dataset.CNNDataset
    pmt_positions_file: /fast_scratch/WatChMaL/data/T2K/image_files/skdetsim_imagefile.npy
    channel_scaling:
      time: [950, 10]
model:
  _target_: watchmal.model.resnet.resnet18
  num_input_channels: 2
  num_output_channels: 3
  stride: 1
  kernelSize: 1
  dropout_p: 0.2
engine:
  _target_: watchmal.engine.regression.RegressionEngine
  truth_key: 'positions'
tasks:
  train:
    epochs: 3
    val_interval: 100
    num_val_batches: 50
    checkpointing: false
    loss:
      _target_: torch.nn.HuberLoss
      delta: 0.1
    data_loaders:
      train:
        split_key: train_idxs
        batch_size: 80
        num_workers: 3
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
      validation:
        split_key: val_idxs
        batch_size: 256
        num_workers: 3
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
    optimizers:
      _target_: torch.optim.Adam
      lr: 0.001
      weight_decay: 0
  evaluate:
    data_loaders:
      test:
        split_key: test_idxs
        batch_size: 512
        num_workers: 4
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
gpu_list: 
- 0
- 1
seed: null
dump_path: ./outputs/
