data:
  split_path: '/scratch/fcormier/t2k/ml/output_skdetsim/jan23_electrons_forRegression_5M_1/train_val_test_gt200Hits_FC_nFolds20_fold0.npz' 
  dataset:
    h5file: '$SLURM_TMPDIR/digi_combine.hy'
    _target_: watchmal.dataset.cnn.cnn_dataset.CNNDatasetDeadPMT
    pmt_positions_file: /fast_scratch/WatChMaL/data/T2K/image_files/skdetsim_imagefile.npy
    use_positions: False
    geometry_file: /home/fcormier/t2k/ml/training/t2k_ml_training/data/geofile_skdetsim.npz
    channel_scaling:
      time: [400, 1000]
    change_dead_pmts: True
    dead_pmt_var: 0.01
    dead_pmt_rate: 0.01
    use_hit_mask: True
model:
  _target_: watchmal.model.resnet.resnet18
  num_input_channels: 3
  num_output_channels: 1
  stride: 1
  kernelSize: 1
  dropout_p: 0.
  conv_pad_mode: 'circular'
engine:
  _target_: watchmal.engine.regression.RegressionEngine
  truth_key: 'momenta'
tasks:
  train:
    epochs: 50
    val_interval: 10
    num_val_batches: 10
    checkpointing: false
    loss:
      _target_: torch.nn.HuberLoss
      delta: 0.1
    data_loaders:
      train:
        split_key: train_idxs
        batch_size: 50
        num_workers: 2
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
      validation:
        split_key: val_idxs
        batch_size: 200
        num_workers: 2
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
    optimizers:
      _target_: torch.optim.Adam
      lr: 0.01
      weight_decay: 0
    scheduler:
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.8
  evaluate:
    data_loaders:
      test:
        split_key: test_idxs
        batch_size: 1000
        num_workers: 2
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
gpu_list: 
- 4
- 5
- 6
- 7
seed: null
dump_path: ./outputs/
