data:
  split_path: /fast_scratch/WatChMaL/data/T2K/nov18_emu_fullCylinder_500k_1/train0.7_val0.15_test0.15000000000000005.npz
  dataset:
    h5file: '/fast_scratch/WatChMaL/data/T2K/nov18_emu_fullCylinder_500k_1/combine_combine.hy'
    _target_: watchmal.dataset.cnn.cnn_dataset.CNNDataset
    pmt_positions_file: /fast_scratch/WatChMaL/data/T2K/image_files/sk_wcsim_imagefile.npz
    collapse_arrays: false
model:
  _recursive_: false
  _target_: watchmal.model.classifier.Classifier
  num_classes: 2
  feature_extractor:
    _target_: watchmal.model.resnet.resnet18
    num_input_channels: 2
    num_output_channels: 2
  classification_network:
    _target_: watchmal.model.classifier.PassThrough
engine:
  _target_: watchmal.engine.engine_classifier.ClassifierEngine
tasks:
  train:
    epochs: 20
    report_interval: 100
    val_interval: 100
    num_val_batches: 32
    checkpointing: false
    data_loaders:
      train:
        split_key: train_idxs
        batch_size: 128
        num_workers: 4
        transforms:
        - horizontal_flip
        - vertical_flip
        - front_back_reflection
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
      validation:
        split_key: val_idxs
        batch_size: 512
        num_workers: 4
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
    optimizers:
      _target_: torch.optim.Adam
      lr: 0.001
      weight_decay: 0
  restore_best_state:
    placeholder: configs can't be empty
  evaluate:
    data_loaders:
      test:
        split_key: test_idxs
        batch_size: 512
        num_workers: 4
        sampler:
          _target_: watchmal.dataset.samplers.SubsetSequentialSampler
gpu_list: 
- 6
- 7
seed: null
dump_path: ./outputs/
