data:
  split_path: '/scratch/fcormier/t2k/ml/output_indices/jan23_electrons_forRegression_5M_1/train_val_test_gt100Hits_nFolds20_fold2.npz' 
  dataset:
    h5file: '$SLURM_TMPDIR/digi_combine.hy'
    _target_: watchmal.dataset.cnn.cnn_dataset.CNNDataset
    pmt_positions_file: /scratch/fcormier/t2k/ml/image_files/skdetsim_imagefile.npy
    channel_scaling:
      time: [950, 10]
model:
  _target_: watchmal.model.resnet.resnet18
  num_input_channels: 2
  num_output_channels: 3
  stride: 1
  kernelSize: 1
  dropout_p: 0.2
engine:
  _target_: watchmal.engine.regression.RegressionEngine
  truth_key: 'positions'
tasks:
  train:
    epochs: 30
    val_interval: 100
    num_val_batches: 2
    checkpointing: false
    loss:
      _target_: torch.nn.HuberLoss
      delta: 0.01
    data_loaders:
      train:
        split_key: train_idxs
        batch_size: 500
        num_workers: 12
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
      validation:
        split_key: val_idxs
        batch_size: 1200
        num_workers: 6
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
    optimizers:
      _target_: torch.optim.Adam
      lr: 0.1
      weight_decay: 0
    scheduler:
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.8
  evaluate:
    data_loaders:
      test:
        split_key: test_idxs
        batch_size: 2000
        num_workers: 6
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
gpu_list:
  - 0
  - 1
  - 2
  - 3
seed: null
dump_path: ./outputs/
