data:
  split_path: '/fast_scratch/fcormier/t2k/ml/wcsim/jul12_egamma_rangeBall/train_val_test_nFolds4_fold1.npz' 
  dataset:
    h5file: '/fast_scratch/fcormier/t2k/ml/wcsim/jul12_egamma_rangeBall/combine_combine.hy'
    _target_: watchmal.dataset.cnn.cnn_dataset.CNNDataset
    pmt_positions_file: /fast_scratch/WatChMaL/data/T2K/image_files/sk_wcsim_imagefile.npz
model:
  _recursive_: false
  _target_: watchmal.model.classifier.Classifier
  num_classes: 2
  feature_extractor:
    _target_: watchmal.model.resnet.resnet34
    num_input_channels: 2
    num_output_channels: 2
  classification_network:
    _target_: watchmal.model.classifier.PassThrough
engine:
  _target_: watchmal.engine.engine_classifier.ClassifierEngine
tasks:
  train:
    epochs: 2
    report_interval: 100
    val_interval: 100
    num_val_batches: 32
    checkpointing: false
    early_stopping_patience: 3
    restore_best_state: false
    data_loaders:
      train:
        split_key: train_idxs
        batch_size: 64
        num_workers: 4
        transforms:
        - horizontal_flip
        - vertical_flip
        - front_back_reflection
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
      validation:
        split_key: val_idxs
        batch_size: 128
        num_workers: 4
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
    optimizers:
      _target_: torch.optim.Adam
      lr: 0.001
      weight_decay: 0
    scheduler:
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.8
  evaluate:
    data_loaders:
      test:
        split_key: test_idxs
        batch_size: 128
        num_workers: 4
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
gpu_list: 
- 4
- 5
seed: null
dump_path: ./outputs/
