data:
  split_path: '//fast_scratch_2/fcormier/t2k/ml/data/oct20_combine_flatE/train_val_test_nFolds3_fold0.npz' 
  dataset:
    h5file: '/fast_scratch_2/fcormier/t2k/ml/data/oct20_combine_flatE/combine_combine.hy'
    _target_: watchmal.dataset.cnn.cnn_dataset.CNNDatasetScale
    pmt_positions_file: /fast_scratch/WatChMaL/data/T2K/image_files/skdetsim_imagefile.npy
    use_positions: False
    geometry_file: /home/fcormier/t2k/ml/t2k_ml_training/data/geofile_skdetsim.npz
    channel_scaling:
      time: [400, 1000]
    dead_pmt_rate: 0
    dead_pmt_seed: null
    channel_scaler:
      # file location for fitted scaler (for precomputed). Must be a list (surrounded by [])
      fitted_scaler:  ['/home/thoriba/t2k2/t2k_ml_training/chain_scaler_1_quantile_normal.joblib', '/home/thoriba/t2k2/t2k_ml_training/chain_scaler_2_minmax.joblib']
      scaler_type: 'minmax'
      sample_size: 10000
      dataset_index_file: null
      transform_per_batch: True
model:
  _target_: watchmal.model.resnet.resnet34
  num_input_channels: 2
  num_output_channels: 3
  stride: 1
  kernelSize: 1
  dropout_p: 0.
engine:
  _target_: watchmal.engine.regression.RegressionEngine
  truth_key: 'positions'
tasks:
  restore_best_state:
    name: RegressionEngine_ResNet
  evaluate:
    loss:
      _target_: torch.nn.HuberLoss
      delta: 0.1
    optimizers:
      _target_: torch.optim.Adam
      lr: 0.001
      weight_decay: 0
    data_loaders:
      test:
        split_key: test_idxs
        batch_size: 300
        num_workers: 1
        sampler:
          _target_: torch.utils.data.sampler.SubsetRandomSampler
          # _target_: torch.utils.data.sampler.SequentialSampler

gpu_list:
  - 7
seed: null
dump_path: ./outputs/
