train:
  learning_rate: 0.0001
  weight_decay: 0.0001
  gpus:
    - 0

defaults:
  - engine: classifier
  - model: classifier
  - model/feature_extractor: resnet18
  - model/classification_network: resnet_fc
  - data: cnn_mpmt_postveto_nomichel
  - data/dataset: cnn_mpmt
