train:
  epochs: 7
  report_interval: 100
  val_interval: 400
  num_val_batches: 8

  learning_rate: 0.001
  weight_decay: 0
  gpu_list:
    - 4
    - 5
  dump_path: './outputs/'

defaults:
  - engine: classifier
  - model: classifier
  - model/feature_extractor: pointnet
  - model/classification_network: pointnet_fc
  - data: iwcd_postveto_nomichel
  - data/dataset: iwcd_pointnet
  - train_model_dir: ${defaults.0.engine}_${defaults.2.model/feature_extractor}
    optional: true
