train:
  epochs: 1
  report_interval: 20
  num_vals: 5431
  num_val_batches: 3

  learning_rate: 0.0001
  weight_decay: 0.0001
  device: 'gpu'
  gpu_list:
    - 7
  dump_path: './outputs/'

defaults:
  - engine: classifier
  - model: classifier
  - model/feature_extractor: resnet18
  - model/classification_network: resnet_fc
  - data: cnn_mpmt_postveto_nomichel
  - data/dataset: cnn_mpmt
