train:
  epochs: 2
  report_interval: 100
  num_vals: 54
  num_val_batches: 50

  learning_rate: 0.001
  weight_decay: 0.0001
  gpu_list:
    - 6
    - 7
  dump_path: './outputs/'

defaults:
  - engine: classifier
  - model: classifier
  - model/feature_extractor: pointnet
  - model/classification_network: pointnet_fc
  - data: iwcd_postveto_nomichel
  - data/dataset: iwcd_pointnet
